In [89]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Import Libaries Required

In [90]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Load Dataset
### Purpose: Extract raw dataset without modification

In [91]:
df = pd.read_csv("/content/drive/MyDrive/gen ai capstone/IN_youtube_trending_data.csv")

 ## Initial Data Inspection

In [92]:
df.sample(5)

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
235146,nengwLtEeYI,గంటలో 100కు పైన పప్పు చెక్కలు👉Extra క్రిస్పీగా...,2024-01-08T05:30:18Z,UCP2JIsLWvpPoS82e49YAAlw,Amma Chethi Vanta,26,2024-01-13T00:00:00Z,pappu chekkalu|chekkalu recipe in telugu|chekk...,949281,9876,0,265,https://i.ytimg.com/vi/nengwLtEeYI/default.jpg,False,False,Today I'm going to share you sankranthi specia...
187679,RSP1IPdvVhg,Nelson & Redin Kingsley😂 | Ananda Vikatan Cine...,2023-04-17T08:30:05Z,UCjF5ecCYXFDvR0UY9GcfnoA,Cinema Vikatan,24,2023-04-20T00:00:00Z,vikatan cinema awards|ananda vikatan cinema aw...,402642,12883,0,328,https://i.ytimg.com/vi/RSP1IPdvVhg/default.jpg,False,False,#nelson #redinkingsley #avcinemaawards #vikata...
41956,8XFj-ri0WeU,OnePlus 9 Pro Durability Test! - Who is Hassel...,2021-03-23T15:00:05Z,UCWFKCr40YwOZQx8FHU_ZqqQ,JerryRigEverything,26,2021-03-27T00:00:00Z,OnePlus 9 Pro|OnePlus|OnePlus 9|One Plus|Smart...,1580277,80580,2003,4302,https://i.ytimg.com/vi/8XFj-ri0WeU/default.jpg,False,False,Its time to durability test the new OnePlus 9 ...
203141,-Qk34SH1Hpw,Bigg Boss with Indian Youtubers @triggeredinsa...,2023-07-12T14:13:55Z,UC6lVSi_MZ5IZPECkOU0oXoA,Hows Hardy,1,2023-07-14T00:00:00Z,bigg boss|Neon man|Newz boi|Bigg boss ott|Big ...,326298,30392,0,2052,https://i.ytimg.com/vi/-Qk34SH1Hpw/default.jpg,False,False,#Biggboss #fukrainsaan #trigerredinsaan #bigg...
164067,qvfBxNQY_44,ATTITUDE KA BAAP || Warangal Vandhana || The M...,2022-12-10T10:30:20Z,UCj-AT5lRHz4n-_lmbt6rr3w,The Mix,24,2022-12-12T00:00:00Z,The Mix|Attitude ka Baap|Warangal vandhana|The...,778396,34453,0,1167,https://i.ytimg.com/vi/qvfBxNQY_44/default.jpg,False,False,Watch 'Aha Naa Pellanta' on Zee5 here: https:/...

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251277 entries, 0 to 251276
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   video_id           251277 non-null  object
 1   title              251277 non-null  object
 2   publishedAt        251277 non-null  object
 3   channelId          251277 non-null  object
 4   channelTitle       251276 non-null  object
 5   categoryId         251277 non-null  int64
 6   trending_date      251277 non-null  object
 7   tags               251277 non-null  object
 8   view_count         251277 non-null  int64
 9   likes              251277 non-null  int64
 10  dislikes           251277 non-null  int64
 11  comment_count      251277 non-null  int64
 12  thumbnail_link     251277 non-null  object
 13  comments_disabled  251277 non-null  bool
 14  ratings_disabled   251277 non-null  bool
 15  description        231822 non-null  object
dtypes: bool(2), int64(5), object(9)
memory usage: 27.3+ MB

In [94]:
df.describe()

          categoryId    view_count         likes      dislikes  comment_count
count  251277.000000  2.512770e+05  2.512770e+05  2.512770e+05   2.512770e+05
mean       20.861448  2.793858e+06  1.389707e+05  2.333248e+03   8.246164e+03
std         6.040176  6.979626e+06  3.941973e+05  7.199925e+04   7.023638e+04
min         1.000000  0.000000e+00  0.000000e+00  0.000000e+00   0.000000e+00
25%        20.000000  3.779310e+05  1.204900e+04  0.000000e+00   3.420000e+02
50%        24.000000  9.474340e+05  3.699100e+04  0.000000e+00   1.123000e+03
75%        24.000000  2.420593e+06  1.161690e+05  7.180000e+02   3.951000e+03
max        29.000000  2.644074e+08  1.611524e+07  1.234147e+07   6.738565e+06

In [95]:
df.isnull().sum()

video_id                 0
title                    0
publishedAt              0
channelId                0
channelTitle             1
categoryId               0
trending_date            0
tags                     0
view_count               0
likes                    0
dislikes                 0
comment_count            0
thumbnail_link           0
comments_disabled        0
ratings_disabled         0
description          19455
dtype: int64

In [96]:
df.isnull().mean()*100

video_id             0.000000
title                0.000000
publishedAt          0.000000
channelId            0.000000
channelTitle         0.000398
categoryId           0.000000
trending_date        0.000000
tags                 0.000000
view_count           0.000000
likes                0.000000
dislikes             0.000000
comment_count        0.000000
thumbnail_link       0.000000
comments_disabled    0.000000
ratings_disabled     0.000000
description          7.742452
dtype: float64

## HANDLE MISSING VALUES
### Purpose: Ensure no null issues in analytics

In [97]:
df['description'] = df['description'].fillna(np.nan)
df['tags'] = df['tags'].fillna('')

##DROP IRRELEVANT COLUMNS
### Purpose: Remove non-analytical fields

In [98]:
df.drop(['thumbnail_link'], axis=1, inplace=True)

## DATATYPE CONVERSION
### Purpose: Enable time-based analysis

In [99]:
df['publish_time'] = pd.to_datetime(df['publishedAt'])
df['trending_date'] = pd.to_datetime(df['trending_date'])

## REMOVE INVALID RECORDS
### Purpose: Ensure data quality

In [100]:
df = df[df['view_count'] > 0]

## REMOVE DUPLICATES
### Purpose: Avoid duplicate daily entries

In [101]:
df = df.drop_duplicates(subset=['video_id', 'trending_date'])

##FEATURE ENGINEERING
### Purpose: Create analytical metrics

In [102]:
# Engagement metrics
df['likes_ratio'] = df['likes'] / df['view_count']
df['comments_ratio'] = df['comment_count'] / df['view_count']

In [103]:
# Time-based features
df['publish_date'] = df['publish_time'].dt.date
df['publish_hour'] = df['publish_time'].dt.hour

df['trending_year'] = df['trending_date'].dt.year
df['trending_month'] = df['trending_date'].dt.month
df['trending_day'] = df['trending_date'].dt.day_name()

In [108]:
# Virality metric
df['days_to_trend'] = (
    df['trending_date']-
    df['publish_time']
).dt.days
df['days_to_trend'] = df['days_to_trend'].apply(lambda x: x if x >= 0 else 0)

##TREND DURATION FEATURE
### Purpose: Measure how long videos stay trending

In [109]:
trend_days = df.groupby('video_id')['trending_date'].nunique()
df['trend_duration'] = df['video_id'].map(trend_days)

## TAG CLEANING - BASIC NORMALIZATION
### Purpose: Standardize tag format

In [110]:
import re

def clean_tags(tags):
    if tags == '[none]' or tags == '':
        return ''

    tags = tags.lower()  # normalize case
    tags = tags.replace('|', ' ')  # replace separator

    # remove special characters
    tags = re.sub(r'[^a-zA-Z ]', '', tags)

    return tags

df['tags'] = df['tags'].apply(clean_tags)

## REMOVE DUPLICATE TAG WORDS
### Purpose: Avoid repetition like "music music song"

In [111]:
def remove_duplicate_words(text):
    words = text.split()
    return ' '.join(set(words))

df['tags'] = df['tags'].apply(remove_duplicate_words)

## TAG COUNT FEATURE
### Purpose: Measure metadata richness

In [112]:
df['tag_count'] = df['tags'].apply(lambda x: 0 if x == '[none]' else len(x.split('|')))

In [115]:
df.sample(10)

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,...,likes_ratio,comments_ratio,publish_date,publish_hour,trending_year,trending_month,trending_day,days_to_trend,trend_duration,tag_count
205229,-_w-AdvPS2Q,INDIA-A v BANGLADESH-A | Highlights | ACC Men'...,2023-07-21T16:16:40Z,UCF10AG_t1AYW3mlmX7g1VJA,FanCode,17,2023-07-25 00:00:00+00:00,pakistan trending cricket dhull riyan banglade...,4376450,71358,...,0.016305,0.000953,2023-07-21,16,2023,7,Tuesday,3,6,1
97494,HmIwqgc4V7Q,HOSANNA MINISTRIES 2022 NEW YEAR SONG(OFFICIAL...,2021-12-31T16:21:40Z,UC9_NSapcLdSn0sZgdKCgkCA,HOSANNA MINISTRIES - RJY,10,2022-01-05 00:00:00+00:00,official trending wesley dhinakaran rajahmundr...,497386,0,...,0.000000,0.000000,2021-12-31,16,2022,1,Wednesday,4,5,1
41358,TxXfg_wPcoQ,My Birthday Blast 🥳 | Suhana | Basheer Bashi |...,2021-03-19T09:30:58Z,UC4U5j8zZxVT9xYfXSDKN7aQ,Suhana,22,2021-03-24 00:00:00+00:00,none,562721,20960,...,0.037248,0.006003,2021-03-19,9,2021,3,Wednesday,4,4,1
63470,xqgZHgHjWdE,Special 26 | स्पेशल 26 | Scene 12 | CBI Got Pl...,2021-07-13T03:30:20Z,UCs56ffejFhWlCvlvRIdpb9Q,Viacom18 Studios,24,2021-07-13 00:00:00+00:00,scenes film studios movies fake agarwal movie ...,533194,11206,...,0.021017,0.000758,2021-07-13,3,2021,7,Tuesday,0,2,1
210033,hHChtzRhtq4,Abhishek Se Milne Manisha Rani Aayi,2023-08-17T09:50:00Z,UCHDQOZjxuSm0-LgLQtMeCqw,Dimple Malhan Vlogs,22,2023-08-21 00:00:00+00:00,nischay hub shorts family dimple wanderers bos...,11812725,743517,...,0.062942,0.003424,2023-08-17,9,2023,8,Monday,3,6,1
177608,TPghsRsQBlo,THE RETURN OF MINECRAFT | MALAYALAM | Soloviner,2023-02-19T06:00:09Z,UCfWs_St76QGwtL2moa_Y_tg,SoloViner XD,20,2023-02-23 00:00:00+00:00,none,159475,17788,...,0.111541,0.006766,2023-02-19,6,2023,2,Thursday,3,4,1
157770,zuVV9Y55gvc,Ranjithame - Varisu Lyric Song (Tamil) | Thala...,2022-11-05T12:00:42Z,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,10,2022-11-08 00:00:00+00:00,singing vijay song movies lyric tamil thaman r...,27563525,1574905,...,0.057137,0.002682,2022-11-05,12,2022,11,Tuesday,2,9,1
41634,gq739sf0-lg,AMMI'S HYDERABADI CHICKEN KHORMA #FUNNYCOOKING,2021-03-25T14:54:53Z,UCWl6q0hPkMHHunZYduRL2Yg,Hyderabad Diaries More,23,2021-03-26 00:00:00+00:00,diaries hilarious indian desi funny comedy gam...,152709,12524,...,0.082012,0.007380,2021-03-25,14,2021,3,Friday,0,4,1
98005,_mgfk7ICmGw,WELCOME BACK YOUTUBE | BGMI,2022-01-06T20:35:29Z,UC8pVSDbDpITTiPovuygOn8Q,Ghatak Gaming,20,2022-01-08 00:00:00+00:00,none,289694,31100,...,0.107355,0.000635,2022-01-06,20,2022,1,Saturday,1,3,1
158087,2bHA8qpehKQ,BIG BREAKING: India in Semis as South Africa L...,2022-11-06T03:28:46Z,UCVXCo0W9pk2dDkEBNLhTt7A,Sports Tak,17,2022-11-09 00:00:00+00:00,sa sportstak bang pakistan cricket zim tak ned...,1436809,37918,...,0.026390,0.001927,2022-11-06,3,2022,11,Wednesday,2,4,1

In [118]:
df['has_description'] = df['description'].apply(
    lambda x: False if pd.isna(x) or x.strip() == '' else True
)

In [119]:
df.drop(['description'], axis=1, inplace=True)

In [123]:
df.to_csv('/content/drive/MyDrive/gen ai capstone/cleaned_youtube_data.csv', index=False)

In [128]:
df.isnull().sum()

video_id             0
title                0
publishedAt          0
channelId            0
channelTitle         1
categoryId           0
trending_date        0
tags                 0
view_count           0
likes                0
dislikes             0
comment_count        0
comments_disabled    0
ratings_disabled     0
publish_time         0
likes_ratio          0
comments_ratio       0
publish_date         0
publish_hour         0
trending_year        0
trending_month       0
trending_day         0
days_to_trend        0
trend_duration       0
tag_count            0
has_description      0
dtype: int64

In [129]:
df = df.dropna()

In [133]:
# Fix datetime
df['publishedAt'] = pd.to_datetime(df['publishedAt'])
df['trending_date'] = pd.to_datetime(df['trending_date'])

# Rename for consistency
df.rename(columns={'view_count': 'views'}, inplace=True)

# Create engagement rate
df['engagement_rate'] = (df['likes'] + df['comment_count']) / df['views']

# Monetization proxy (very important)
df['monetization_score'] = df['views'] * df['engagement_rate']

/tmp/ipykernel_3394/3635507302.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['publishedAt'] = pd.to_datetime(df['publishedAt'])
/tmp/ipykernel_3394/3635507302.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['trending_date'] = pd.to_datetime(df['trending_date'])
/tmp/ipykernel_3394/3635507302.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'view_count': 'views'}, inplace=True)
/tmp/ipykernel_3394/3635507302.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['engagement_rate'] = (df['likes'] + df['comment_count']) / df['views']
/tmp/ipykernel_3394/3635507302.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['monetization_score'] = df['views'] * df['engagement_rate']

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 248094 entries, 0 to 251276
Data columns (total 28 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   video_id            248094 non-null  object
 1   title               248094 non-null  object
 2   publishedAt         248094 non-null  datetime64[ns, UTC]
 3   channelId           248094 non-null  object
 4   channelTitle        248094 non-null  object
 5   categoryId          248094 non-null  int64
 6   trending_date       248094 non-null  datetime64[ns, UTC]
 7   tags                248094 non-null  object
 8   views               248094 non-null  int64
 9   likes               248094 non-null  int64
 10  dislikes            248094 non-null  int64
 11  comment_count       248094 non-null  int64
 12  comments_disabled   248094 non-null  bool
 13  ratings_disabled    248094 non-null  bool
 14  publish_time        248094 non-null  datetime64[ns, UTC]
 15  likes_ratio         248094 non-null  float64
 16  comments_ratio      248094 non-null  float64
 17  publish_date        248094 non-null  object
 18  publish_hour        248094 non-null  int32
 19  trending_year       248094 non-null  int32
 20  trending_month      248094 non-null  int32
 21  trending_day        248094 non-null  object
 22  days_to_trend       248094 non-null  int64
 23  trend_duration      248094 non-null  int64
 24  tag_count           248094 non-null  int64
 25  has_description     248094 non-null  bool
 26  engagement_rate     248094 non-null  float64
 27  monetization_score  248094 non-null  float64
dtypes: bool(3), datetime64[ns, UTC](3), float64(4), int32(3), int64(8), object(7)
memory usage: 47.1+ MB

In [135]:
df.to_csv('/content/drive/MyDrive/gen ai capstone/cleaned_indias_youtube_data.csv', index=False)