In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Import Libaries Required

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Load Dataset
### Purpose: Extract raw dataset without modification

In [3]:
df = pd.read_csv("/content/drive/MyDrive/gen ai capstone/IN_youtube_trending_data.csv")

 ## Initial Data Inspection

In [4]:
df.sample(5)

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
191422,ahYUmGRXQWM,Saath Nibhaana Saathiya | साथ निभाना साथिया | ...,2023-05-10T09:40:00Z,UC-LPIU24bQXVljUXivKEeRQ,StarPlus,24,2023-05-11T00:00:00Z,Romantic|Comedy|Magic|Dance|Emotional|Drama|So...,1041914,9521,0,133,https://i.ytimg.com/vi/ahYUmGRXQWM/default.jpg,False,False,Click here to Subscribe *Star Plus* : https://...
119198,QaBIuvCp7Z0,I BROKE MY ARM (STORYTIME) FT. @Triggered Insaan,2022-04-22T09:42:42Z,UC1k1Gf6AbCSuv4CVzOQLLCw,I. M. Bixu,20,2022-04-25T00:00:00Z,triggered insaan|bixu|i m bixu|im bixu|story t...,701208,79770,0,5745,https://i.ytimg.com/vi/QaBIuvCp7Z0/default.jpg,False,False,"Wassup Gamers,Today I will be doing a Story Ti..."
36887,LWyFtvxRZjs,Barathi Kannamma | 1st to 6th March 2021 - Promo,2021-03-01T05:56:24Z,UCvrhwpnp2DHYQ1CbXby9ypQ,Vijay Television,24,2021-03-02T00:00:00Z,Star|Star Vijay TV|Vijay TV|Vijay|Redefining E...,3250107,56438,1333,1412,https://i.ytimg.com/vi/LWyFtvxRZjs/default.jpg,False,False,#BarathiKannamma #VijayTV #VijayTelevision #St...
14816,eRMAiKIgqHA,"Naayagi Episode 715, 28/10/2020",2020-10-28T16:00:09Z,UC-lJ-F5mlPP6SYPkkq6gjwA,VikatanTV,24,2020-10-29T00:00:00Z,SunTv|VikatanTV|Tamil Serial|Tamil Programme|T...,750747,9471,906,598,https://i.ytimg.com/vi/eRMAiKIgqHA/default.jpg,False,False,Vallamai Tharayo - https://www.youtube.com/pla...
137831,abXosen_OX4,Pelli ayina tarvata part-62 ma akka vachhindi 😠😂😂,2022-07-26T03:48:05Z,UCL0pM5-vrLp3Oy9PXzpqXpA,prashu__baby,24,2022-07-28T00:00:00Z,[None],4521753,345376,0,362,https://i.ytimg.com/vi/abXosen_OX4/default.jpg,False,False,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251277 entries, 0 to 251276
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   video_id           251277 non-null  object
 1   title              251277 non-null  object
 2   publishedAt        251277 non-null  object
 3   channelId          251277 non-null  object
 4   channelTitle       251276 non-null  object
 5   categoryId         251277 non-null  int64
 6   trending_date      251277 non-null  object
 7   tags               251277 non-null  object
 8   view_count         251277 non-null  int64
 9   likes              251277 non-null  int64
 10  dislikes           251277 non-null  int64
 11  comment_count      251277 non-null  int64
 12  thumbnail_link     251277 non-null  object
 13  comments_disabled  251277 non-null  bool
 14  ratings_disabled   251277 non-null  bool
 15  description        231822 non-null  object
dtypes: bool(2), int64(5), object(9)
memory usage: 27.3+ MB

In [6]:
df.describe()

          categoryId    view_count         likes      dislikes  comment_count
count  251277.000000  2.512770e+05  2.512770e+05  2.512770e+05   2.512770e+05
mean       20.861448  2.793858e+06  1.389707e+05  2.333248e+03   8.246164e+03
std         6.040176  6.979626e+06  3.941973e+05  7.199925e+04   7.023638e+04
min         1.000000  0.000000e+00  0.000000e+00  0.000000e+00   0.000000e+00
25%        20.000000  3.779310e+05  1.204900e+04  0.000000e+00   3.420000e+02
50%        24.000000  9.474340e+05  3.699100e+04  0.000000e+00   1.123000e+03
75%        24.000000  2.420593e+06  1.161690e+05  7.180000e+02   3.951000e+03
max        29.000000  2.644074e+08  1.611524e+07  1.234147e+07   6.738565e+06

In [7]:
df.isnull().sum()

video_id                 0
title                    0
publishedAt              0
channelId                0
channelTitle             1
categoryId               0
trending_date            0
tags                     0
view_count               0
likes                    0
dislikes                 0
comment_count            0
thumbnail_link           0
comments_disabled        0
ratings_disabled         0
description          19455
dtype: int64

In [8]:
df.isnull().mean()*100

video_id             0.000000
title                0.000000
publishedAt          0.000000
channelId            0.000000
channelTitle         0.000398
categoryId           0.000000
trending_date        0.000000
tags                 0.000000
view_count           0.000000
likes                0.000000
dislikes             0.000000
comment_count        0.000000
thumbnail_link       0.000000
comments_disabled    0.000000
ratings_disabled     0.000000
description          7.742452
dtype: float64

## HANDLE MISSING VALUES
### Purpose: Ensure no null issues in analytics

In [9]:
df['description'] = df['description'].fillna(np.nan)
df['tags'] = df['tags'].fillna('')

##DROP IRRELEVANT COLUMNS
### Purpose: Remove non-analytical fields

In [10]:
df.drop(['thumbnail_link'], axis=1, inplace=True)

## DATATYPE CONVERSION
### Purpose: Enable time-based analysis

In [11]:
# Fix datetime
df['publishedAt'] = pd.to_datetime(df['publishedAt'])

df['publish_time'] = pd.to_datetime(df['publishedAt'])
df['trending_date'] = pd.to_datetime(df['trending_date'])

## REMOVE INVALID RECORDS
### Purpose: Ensure data quality

In [12]:
df = df[df['view_count'] > 0]

## REMOVE DUPLICATES
### Purpose: Avoid duplicate daily entries

In [13]:
df = df.drop_duplicates(subset=['video_id', 'trending_date'])

##FEATURE ENGINEERING
### Purpose: Create analytical metrics

In [14]:
# Engagement metrics
df['likes_ratio'] = df['likes'] / df['view_count']
df['comments_ratio'] = df['comment_count'] / df['view_count']

In [15]:
# Time-based features
df['publish_date'] = df['publish_time'].dt.date
df['publish_hour'] = df['publish_time'].dt.hour

df['trending_year'] = df['trending_date'].dt.year
df['trending_month'] = df['trending_date'].dt.month
df['trending_day'] = df['trending_date'].dt.day_name()

In [16]:
# Virality metric
df['days_to_trend'] = (
    df['trending_date']-
    df['publish_time']
).dt.days
df['days_to_trend'] = df['days_to_trend'].apply(lambda x: x if x >= 0 else 0)

##TREND DURATION FEATURE
### Purpose: Measure how long videos stay trending

In [17]:
trend_days = df.groupby('video_id')['trending_date'].nunique()
df['trend_duration'] = df['video_id'].map(trend_days)

## TAG CLEANING - BASIC NORMALIZATION
### Purpose: Standardize tag format

In [18]:
import re

def clean_tags(tags):
    if tags == '[none]' or tags == '':
        return ''

    tags = tags.lower()  # normalize case
    tags = tags.replace('|', ' ')  # replace separator

    # remove special characters
    tags = re.sub(r'[^a-zA-Z ]', '', tags)

    return tags

df['tags'] = df['tags'].apply(clean_tags)

## REMOVE DUPLICATE TAG WORDS
### Purpose: Avoid repetition like "music music song"

In [19]:
def remove_duplicate_words(text):
    words = text.split()
    return ' '.join(set(words))

df['tags'] = df['tags'].apply(remove_duplicate_words)

## TAG COUNT FEATURE
### Purpose: Measure metadata richness

In [20]:
df['tag_count'] = df['tags'].apply(lambda x: 0 if x == '[none]' else len(x.split(' ')))

In [21]:
df['tag_count']

0         30
1          1
2         19
3         21
4         27
          ..
251272    20
251273    14
251274     4
251275    16
251276    36
Name: tag_count, Length: 248095, dtype: int64

In [22]:
df.sample(10)

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,...,likes_ratio,comments_ratio,publish_date,publish_hour,trending_year,trending_month,trending_day,days_to_trend,trend_duration,tag_count
3215,w1yBV6cXRA8,Maska (Behind The Scenes) | Shirley Setia | Ne...,2020-08-26 10:14:48+00:00,UC_c7EFVXxmQMjj5E2CchGXg,Shirley Setia,24,2020-08-28 00:00:00+00:00,songs bollywood jaffery actor setia koirala ne...,184399,14260,...,0.077332,0.011876,2020-08-26,10,2020,8,Friday,1,2,20
183517,oEBC1Or8teQ,JIND MAHIYA: Pooh In Korea & Pravisht Mishra |...,2023-03-27 05:30:41+00:00,UCLsMef624nZ4ME6WoSElPTg,Voilà! Digi,10,2023-03-28 00:00:00+00:00,bhatt songs official hindi pravisht saaj video...,924802,90165,...,0.097497,0.005536,2023-03-27,5,2023,3,Tuesday,0,6,29
245221,4cu-eB_9AKk,Hotstar Specials Lootere | Official Trailer | ...,2024-03-06 05:32:37+00:00,UC0PTktRYpZXb6On0_zFKWIg,DisneyPlus Hotstar,24,2024-03-09 00:00:00+00:00,disney disneyplus hotstar plus,6774101,10635,...,0.001570,0.000066,2024-03-06,5,2024,3,Saturday,2,5,4
111615,a2WJG8VPCbc,Love War (Official Video) Jassa Dhillon | Gur ...,2022-03-16 04:30:52+00:00,UColNRmGBE3dNzJ89zZZOh2Q,Brown Town Music,10,2022-03-18 00:00:00+00:00,gur sidhu music songs punjabi latest war new j...,1636258,44849,...,0.027409,0.000630,2022-03-16,4,2022,3,Friday,1,5,13
93769,1SO5lmzilC8,Mehbooba Ji : Kay Vee Singh Ft. Ashi Khanna (O...,2021-12-14 10:37:26+00:00,UCticaNjYGCpYXyo4BxM3RWQ,Juke Dock,10,2021-12-17 00:00:00+00:00,singh kayvee all full latest mehbooba new week...,1493194,52358,...,0.035064,0.002317,2021-12-14,10,2021,12,Friday,2,3,22
197513,syGS4d-NhFA,Bloody Daddy movie REVIEW,2023-06-09 03:33:13+00:00,UCUinnqDgIsNFleLdkZKbP-w,BnfTV,24,2023-06-12 00:00:00+00:00,none,579579,38377,...,0.066215,0.001995,2023-06-09,3,2023,6,Monday,2,3,1
251149,_MoIybGhaSQ,Reaction Whistle Podu | Filmy React | The Grea...,2024-04-14 13:39:04+00:00,UCQkLGM2WgwIcTaQc82IS_nQ,Filmy React,24,2024-04-15 00:00:00+00:00,none,56801,4634,...,0.081583,0.003732,2024-04-14,13,2024,4,Monday,0,1,1
85702,aeKpQYSybF8,Diwali special Mehndi design for hands |Simple...,2021-11-03 13:55:40+00:00,UCB7XseChdlmAar11r27w17w,Shab's Creation,26,2021-11-05 00:00:00+00:00,creation mehdi mehandi video dizain henna desi...,162940,969,...,0.005947,0.000141,2021-11-03,13,2021,11,Friday,1,2,24
160344,ypkpJRyxgxE,5 Daily Winter Products That You Should Throw ...,2022-11-18 13:30:19+00:00,UCYC6Vcczj8v-Y5OgpEJTFBw,Fit Tuber,26,2022-11-21 00:00:00+00:00,chyawanprash best body which market balm is ro...,480743,27650,...,0.057515,0.002336,2022-11-18,13,2022,11,Monday,2,6,31
86867,FzFaR5cdmgg,AirPods 3 Unboxing With Magsafe Charger #shorts,2021-11-10 12:27:03+00:00,UCwMz3sdmthvWZUrRfscqrbg,Techno Craz,28,2021-11-11 00:00:00+00:00,none,112873,4726,...,0.041870,0.000089,2021-11-10,12,2021,11,Thursday,0,2,1

In [23]:
df['has_description'] = df['description'].apply(
    lambda x: False if pd.isna(x) or x.strip() == '' else True
)

In [24]:
df.drop(['description'], axis=1, inplace=True)

In [25]:
# df.to_csv('/content/drive/MyDrive/gen ai capstone/cleaned_youtube_data.csv', index=False)

In [26]:
df.isnull().sum()

video_id             0
title                0
publishedAt          0
channelId            0
channelTitle         1
categoryId           0
trending_date        0
tags                 0
view_count           0
likes                0
dislikes             0
comment_count        0
comments_disabled    0
ratings_disabled     0
publish_time         0
likes_ratio          0
comments_ratio       0
publish_date         0
publish_hour         0
trending_year        0
trending_month       0
trending_day         0
days_to_trend        0
trend_duration       0
tag_count            0
has_description      0
dtype: int64

In [27]:
df = df.dropna()

In [28]:

# Rename for consistency
df.rename(columns={'view_count': 'views'}, inplace=True)

# Create engagement rate
df['engagement_rate'] = (df['likes'] + df['comment_count']) / df['views']

# Monetization proxy (very important)
df['monetization_score'] = df['views'] * df['engagement_rate']

### Category Mapping

In [29]:
category_map = {
    24: "Entertainment",
    10: "Music",
    20: "Gaming",
    23: "Comedy",
    22: "People & Blogs",
    25: "News & Politics",
    17: "Sports",
    1: "Film & Animation",
    26: "Howto & Style",
    28: "Science & Technology",
    27: "Education",
    2: "Autos & Vehicles",
    19: "Travel & Events",
    15: "Pets & Animals",
    29:'Cultral'
}

In [30]:
df['category_name'] = df['categoryId'].map(category_map)

In [31]:
def time_bucket(hour):
    if 5 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"

df['time_bucket'] = df['publish_hour'].apply(time_bucket)

In [32]:
# STANDARDIZE COLUMN NAMES (SNAKE_CASE)

df.rename(columns={
    'publishedAt': 'published_at',
    'channelId': 'channel_id',
    'channelTitle': 'channel_title',
    'categoryId': 'category_id',
}, inplace=True)

In [33]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)

In [34]:
# =========================================
# FINAL COLUMN ORDERING (DASHBOARD READY)
# =========================================

df = df[[
    # 🔹 1. IDENTIFIERS
    'video_id',
    'title',
    'channel_id',
    'channel_title',
    'category_id',
    'category_name',

    # 🔹 2. TIME (RAW + DERIVED)
    'published_at',
    'publish_time',
    'publish_date',
    'publish_hour',
    'time_bucket',
    'trending_date',
    'trending_year',
    'trending_month',
    'trending_day',

    # 🔹 3. PERFORMANCE (RAW METRICS)
    'views',
    'likes',
    'comment_count',
    'dislikes',

    # 🔹 4. ENGAGEMENT METRICS
    'likes_ratio',
    'comments_ratio',
    'engagement_rate',

    # 🔹 5. VIRALITY & GROWTH
    'days_to_trend',
    'trend_duration',

    # 🔹 6. MONETIZATION
    'monetization_score',

    # 🔹 7. CONTENT FEATURES
    'tags',
    'tag_count',
    'has_description',

    # 🔹 8. FLAGS
    'comments_disabled',
    'ratings_disabled'
]]

In [35]:
df.isnull().sum()

video_id              0
title                 0
channel_id            0
channel_title         0
category_id           0
category_name         0
published_at          0
publish_time          0
publish_date          0
publish_hour          0
time_bucket           0
trending_date         0
trending_year         0
trending_month        0
trending_day          0
views                 0
likes                 0
comment_count         0
dislikes              0
likes_ratio           0
comments_ratio        0
engagement_rate       0
days_to_trend         0
trend_duration        0
monetization_score    0
tags                  0
tag_count             0
has_description       0
comments_disabled     0
ratings_disabled      0
dtype: int64

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 248094 entries, 0 to 251276
Data columns (total 30 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   video_id            248094 non-null  object
 1   title               248094 non-null  object
 2   channel_id          248094 non-null  object
 3   channel_title       248094 non-null  object
 4   category_id         248094 non-null  int64
 5   category_name       248094 non-null  object
 6   published_at        248094 non-null  datetime64[ns, UTC]
 7   publish_time        248094 non-null  datetime64[ns, UTC]
 8   publish_date        248094 non-null  object
 9   publish_hour        248094 non-null  int32
 10  time_bucket         248094 non-null  object
 11  trending_date       248094 non-null  datetime64[ns, UTC]
 12  trending_year       248094 non-null  int32
 13  trending_month      248094 non-null  int32
 14  trending_day        248094 non-null  object
 15  views               248094 non-null  int64
 16  likes               248094 non-null  int64
 17  comment_count       248094 non-null  int64
 18  dislikes            248094 non-null  int64
 19  likes_ratio         248094 non-null  float64
 20  comments_ratio      248094 non-null  float64
 21  engagement_rate     248094 non-null  float64
 22  days_to_trend       248094 non-null  int64
 23  trend_duration      248094 non-null  int64
 24  monetization_score  248094 non-null  float64
 25  tags                248094 non-null  object
 26  tag_count           248094 non-null  int64
 27  has_description     248094 non-null  bool
 28  comments_disabled   248094 non-null  bool
 29  ratings_disabled    248094 non-null  bool
dtypes: bool(3), datetime64[ns, UTC](3), float64(4), int32(3), int64(8), object(9)
memory usage: 50.9+ MB

In [37]:
df.sample(5)

,video_id,title,channel_id,channel_title,category_id,category_name,published_at,publish_time,publish_date,publish_hour,...,comments_ratio,engagement_rate,days_to_trend,trend_duration,monetization_score,tags,tag_count,has_description,comments_disabled,ratings_disabled
22463,mm1Em5ElCRE,My Home Tour In My Village || Village Vlog || ...,UCwuVJs7Dr6j3Fc_XM2mP2JA,Its Himaja,10,Music,2020-12-08 07:00:13+00:00,2020-12-08 07:00:13+00:00,2020-12-08,7,...,0.000000,0.031383,2,5,18032.0,return its video room corporate videos diwali ...,38,True,True,False
221006,p8jba1ZGWpM,GTA 5 : Franklin Shinchan & Pinchan Ultimate M...,UCt3mMVAyGhwQb_ZBGp_p85g,Flight Gamer,20,Gaming,2023-10-21 05:25:08+00:00,2023-10-21 05:25:08+00:00,2023-10-21,5,...,0.001113,0.025500,1,4,27783.0,gamer franklin best ultimate upgrading mods pi...,26,True,False,False
186658,b-Fsvy-bvUk,అక్క బాబు కోసం తీసుకున్న బంగారం || Durga Gade ...,UC4ij0nxIZZ9IIhn52BlE4Vw,Durga Gade,26,Howto & Style,2023-04-12 13:02:18+00:00,2023-04-12 13:02:18+00:00,2023-04-12,13,...,0.000390,0.012489,1,3,4228.0,durga actress panjaram durgagade gade savithri...,15,True,False,False
13806,qp8L7lIhSeo,OPPO F17 Pro - Diwali Edition | #BeTheLight To...,UCMoJmRNcc-n8WdesyjQ6i_g,OPPO Mobile India,28,Science & Technology,2020-10-19 13:48:02+00:00,2020-10-19 13:48:02+00:00,2020-10-19,13,...,0.000056,0.003401,3,5,117683.0,diwalivibes festiveseason diwaligifting diwali...,12,True,False,False
21443,qWUsV2Ios8A,India take 1-0 lead after dramatic T20 opener ...,UCkBY0aHJP9BwjZLDYxAQrKg,cricket.com.au,17,Sports,2020-12-04 12:25:13+00:00,2020-12-04 12:25:13+00:00,2020-12-04,12,...,0.000815,0.022610,0,6,422112.0,first manuka canberra oval ti australia india,7,True,False,False

In [38]:
# df.to_csv('/content/drive/MyDrive/gen ai capstone/cleaned_india_youtube_data.csv', index=False)