In [50]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Import Libaries Required

In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Load Dataset
### Purpose: Extract raw dataset without modification

In [52]:
df = pd.read_csv("/content/drive/MyDrive/gen ai capstone/IN_youtube_trending_data.csv")

 ## Initial Data Inspection

In [53]:
df.sample(5)

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
120041,V5qOu5KTa5g,Mere HumSafar Episode 18 | Presented by Sensod...,2022-04-29T19:05:36Z,UC4JCksJF76g_MdzPVBJoC3Q,ARY Digital,24,2022-04-30T00:00:00Z,Pakistani Drama|top pakistani dramas|best paki...,5911336,217420,0,6319,https://i.ytimg.com/vi/V5qOu5KTa5g/default.jpg,False,False,Mere HumSafar Episode 18 | 29th April 2022 | A...
173721,hracg1z5czg,Aakhir Apni New Ninja H2 Superbike Aisi Modify...,2023-01-31T10:14:00Z,UC4GSblxbWPSa1uk5SG3MYIw,The UK07 Rider,22,2023-02-02T00:00:00Z,[None],1688859,184487,0,5785,https://i.ytimg.com/vi/hracg1z5czg/default.jpg,False,False,Giveaway Channel Video - https://youtu.be/1iRJ...
240065,XyF6M6F54Uk,Bana Hi Nahi Tha Jana - Dino James [Official V...,2024-02-06T07:43:24Z,UCtpDorOuxwQ1URGQ0WLIXmQ,Dino James,10,2024-02-09T00:00:00Z,[None],303797,45761,0,2151,https://i.ytimg.com/vi/XyF6M6F54Uk/default.jpg,False,False,“Bana Hi Nahi Tha” is essentially a breakup ba...
161198,F9oBQiH7XXc,In Dubai for recieving an award| Allhamdulilla...,2022-11-22T14:13:12Z,UC2kBDwkqiy7zgH1-M4UtUXQ,Dipika Ki Duniya,22,2022-11-25T00:00:00Z,[None],2606630,141128,0,7579,https://i.ytimg.com/vi/F9oBQiH7XXc/default.jpg,False,False,NaN
124660,wpnayOHzl6E,Sher Bagga (Official Trailer) | Ammy Virk | So...,2022-05-23T04:35:49Z,UCmSHlTXTeRBhkAKQTC7wPXA,Burfi Music,10,2022-05-23T00:00:00Z,ammy virk|ammy virk new movie|burfi music|whit...,1091998,64213,0,3370,https://i.ytimg.com/vi/wpnayOHzl6E/default.jpg,False,False,Daljit Thind and Ammy Virk present you the 'Of...

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251277 entries, 0 to 251276
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   video_id           251277 non-null  object
 1   title              251277 non-null  object
 2   publishedAt        251277 non-null  object
 3   channelId          251277 non-null  object
 4   channelTitle       251276 non-null  object
 5   categoryId         251277 non-null  int64
 6   trending_date      251277 non-null  object
 7   tags               251277 non-null  object
 8   view_count         251277 non-null  int64
 9   likes              251277 non-null  int64
 10  dislikes           251277 non-null  int64
 11  comment_count      251277 non-null  int64
 12  thumbnail_link     251277 non-null  object
 13  comments_disabled  251277 non-null  bool
 14  ratings_disabled   251277 non-null  bool
 15  description        231822 non-null  object
dtypes: bool(2), int64(5), object(9)
memory usage: 27.3+ MB

In [55]:
df.describe()

          categoryId    view_count         likes      dislikes  comment_count
count  251277.000000  2.512770e+05  2.512770e+05  2.512770e+05   2.512770e+05
mean       20.861448  2.793858e+06  1.389707e+05  2.333248e+03   8.246164e+03
std         6.040176  6.979626e+06  3.941973e+05  7.199925e+04   7.023638e+04
min         1.000000  0.000000e+00  0.000000e+00  0.000000e+00   0.000000e+00
25%        20.000000  3.779310e+05  1.204900e+04  0.000000e+00   3.420000e+02
50%        24.000000  9.474340e+05  3.699100e+04  0.000000e+00   1.123000e+03
75%        24.000000  2.420593e+06  1.161690e+05  7.180000e+02   3.951000e+03
max        29.000000  2.644074e+08  1.611524e+07  1.234147e+07   6.738565e+06

In [56]:
df.isnull().sum()

video_id                 0
title                    0
publishedAt              0
channelId                0
channelTitle             1
categoryId               0
trending_date            0
tags                     0
view_count               0
likes                    0
dislikes                 0
comment_count            0
thumbnail_link           0
comments_disabled        0
ratings_disabled         0
description          19455
dtype: int64

In [57]:
df.isnull().mean()*100

video_id             0.000000
title                0.000000
publishedAt          0.000000
channelId            0.000000
channelTitle         0.000398
categoryId           0.000000
trending_date        0.000000
tags                 0.000000
view_count           0.000000
likes                0.000000
dislikes             0.000000
comment_count        0.000000
thumbnail_link       0.000000
comments_disabled    0.000000
ratings_disabled     0.000000
description          7.742452
dtype: float64

## HANDLE MISSING VALUES
### Purpose: Ensure no null issues in analytics

In [58]:
df['description'] = df['description'].fillna(np.nan)
df['tags'] = df['tags'].fillna('')

##DROP IRRELEVANT COLUMNS
### Purpose: Remove non-analytical fields

In [59]:
df.drop(['thumbnail_link'], axis=1, inplace=True)

## DATATYPE CONVERSION
### Purpose: Enable time-based analysis

In [60]:
# Fix datetime
df['publishedAt'] = pd.to_datetime(df['publishedAt'])

df['publish_time'] = pd.to_datetime(df['publishedAt'])
df['trending_date'] = pd.to_datetime(df['trending_date'])

## REMOVE INVALID RECORDS
### Purpose: Ensure data quality

In [61]:
df = df[df['view_count'] > 0]

## REMOVE DUPLICATES
### Purpose: Avoid duplicate daily entries

In [62]:
df = df.drop_duplicates(subset=['video_id', 'trending_date'])

##FEATURE ENGINEERING
### Purpose: Create analytical metrics

In [63]:
# Engagement metrics
df['likes_ratio'] = df['likes'] / df['view_count']
df['comments_ratio'] = df['comment_count'] / df['view_count']

In [64]:
# Time-based features
df['publish_date'] = df['publish_time'].dt.date
df['publish_hour'] = df['publish_time'].dt.hour

df['trending_year'] = df['trending_date'].dt.year
df['trending_month'] = df['trending_date'].dt.month
df['trending_day'] = df['trending_date'].dt.day_name()

In [65]:
# Virality metric
df['days_to_trend'] = (
    df['trending_date']-
    df['publish_time']
).dt.days
df['days_to_trend'] = df['days_to_trend'].apply(lambda x: x if x >= 0 else 0)

##TREND DURATION FEATURE
### Purpose: Measure how long videos stay trending

In [66]:
trend_days = df.groupby('video_id')['trending_date'].nunique()
df['trend_duration'] = df['video_id'].map(trend_days)

## TAG CLEANING - BASIC NORMALIZATION
### Purpose: Standardize tag format

In [67]:
import re

def clean_tags(tags):
    if tags == '[none]' or tags == '':
        return ''

    tags = tags.lower()  # normalize case
    tags = tags.replace('|', ' ')  # replace separator

    # remove special characters
    tags = re.sub(r'[^a-zA-Z ]', '', tags)

    return tags

df['tags'] = df['tags'].apply(clean_tags)

## REMOVE DUPLICATE TAG WORDS
### Purpose: Avoid repetition like "music music song"

In [68]:
def remove_duplicate_words(text):
    words = text.split()
    return ' '.join(set(words))

df['tags'] = df['tags'].apply(remove_duplicate_words)

## TAG COUNT FEATURE
### Purpose: Measure metadata richness

In [69]:
df['tag_count'] = df['tags'].apply(lambda x: 0 if x == '[none]' else len(x.split('|')))

In [70]:
df.sample(10)

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,...,likes_ratio,comments_ratio,publish_date,publish_hour,trending_year,trending_month,trending_day,days_to_trend,trend_duration,tag_count
221254,Qo4SbDh4jRs,BiggBossTelugu7 Promo 1| Dussehra and Bathukam...,2023-10-22 04:27:58+00:00,UCJF4y2nyCCrDKTgA7dxz1Qw,Star Maa,22,2023-10-24 00:00:00+00:00,malli mukunda new murari serial tv krishna sta...,2742033,51183,...,0.018666,0.001310,2023-10-22,4,2023,10,Tuesday,1,2,1
129231,oiEZ-rr1KjI,INDIAN CID IS *SOOO* FUNNY,2022-06-14 05:00:24+00:00,UCeVpStjN-r4QmuI-mmzfRwg,mosambi,22,2022-06-15 00:00:00+00:00,pradyuman chapati hindustani acp hindi reactio...,297418,32873,...,0.110528,0.002606,2022-06-14,5,2022,6,Wednesday,0,2,1
222855,C5JuRbz9ptM,#Chiyaan62 - Announcement Video | Chiyaan Vikr...,2023-10-28 13:40:10+00:00,UCGi0C80SCay7W1nVTujVfCw,HR Pictures,1,2023-11-02 00:00:00+00:00,new update tamil chiyaanvikram riya hr picture...,6477215,118656,...,0.018319,0.000330,2023-10-28,13,2023,11,Thursday,4,6,1
36984,klbN7ASex2g,Asim Riaz Reaction on Rubina Dilaik as Bigg Bo...,2021-02-26 15:49:06+00:00,UCZT_OWY9abyO3V9Rmdvh02w,Viralbollywood,24,2021-03-02 00:00:00+00:00,copying song capying supports record azsim vs ...,802710,22423,...,0.027934,0.002342,2021-02-26,15,2021,3,Tuesday,3,3,1
226203,euipQaMA1eU,Unexpected Support For Barrelakka | Telangana ...,2023-11-19 02:03:30+00:00,UCZ9m4KOh8Ei60428xeGYDCQ,Sakshi TV,25,2023-11-21 00:00:00+00:00,telangana bjp for sakshitv unexpected sakshi e...,207719,4668,...,0.022473,0.001464,2023-11-19,2,2023,11,Tuesday,1,3,1
100254,taBsz7Rmez8,தமிழ்நாட்டு கிராமத்து பொங்கல் கொண்டாட்டம் | Hu...,2022-01-16 11:31:54+00:00,UCQS9wN4pNfQ0VNHJRPqj2OQ,Hussain Manimegalai,24,2022-01-19 00:00:00+00:00,video series vj manimegalai hussain pongal cou...,518234,28176,...,0.054369,0.001999,2022-01-16,11,2022,1,Wednesday,2,2,1
127264,yTSkq5bcisU,Tribute to KK - A Legacy| Sach Keh Raha Hai De...,2022-06-01 06:30:38+00:00,UC_A7K2dXFsTMAciGmnNxy-Q,Saregama Music,10,2022-06-05 00:00:00+00:00,banjarapan songs singer meri romantic alvida s...,1786281,55938,...,0.031315,0.001938,2022-06-01,6,2022,6,Sunday,3,5,1
81940,_i6l0uUDIko,MIDDLE CLASS FAMILY KA FIRST IPHONE || DUSSEHR...,2021-10-14 05:49:41+00:00,UCAn7MPfti8x24dbQ4YQ6iPA,Lokesh Bhardwaj,24,2021-10-17 00:00:00+00:00,coca khazana new family funny dikro sumit the ...,705292,16709,...,0.023691,0.000597,2021-10-14,5,2021,10,Sunday,2,3,1
133399,PjSod2dGyoI,Theatre Sothanaigal | Micset,2022-07-01 15:45:11+00:00,UC5EQWvy59VeHPJz8mDALPxg,Mic Set,23,2022-07-06 00:00:00+00:00,mind sothanaigal new micset tamil episodes sot...,2440281,205823,...,0.084344,0.001756,2022-07-01,15,2022,7,Wednesday,4,6,1
174272,UiMurE8KPWY,Testing Viral Hacks 😳 || Khushi Choudhary,2023-02-03 08:30:28+00:00,UCijX8M8PXJiWL8xvxa-oiMw,khushi Choudhary,22,2023-02-05 00:00:00+00:00,westernclothes hairstyle footwear rivlogs outf...,55443,6400,...,0.115434,0.006980,2023-02-03,8,2023,2,Sunday,1,2,1

In [71]:
df['has_description'] = df['description'].apply(
    lambda x: False if pd.isna(x) or x.strip() == '' else True
)

In [72]:
df.drop(['description'], axis=1, inplace=True)

In [73]:
# df.to_csv('/content/drive/MyDrive/gen ai capstone/cleaned_youtube_data.csv', index=False)

In [74]:
df.isnull().sum()

video_id             0
title                0
publishedAt          0
channelId            0
channelTitle         1
categoryId           0
trending_date        0
tags                 0
view_count           0
likes                0
dislikes             0
comment_count        0
comments_disabled    0
ratings_disabled     0
publish_time         0
likes_ratio          0
comments_ratio       0
publish_date         0
publish_hour         0
trending_year        0
trending_month       0
trending_day         0
days_to_trend        0
trend_duration       0
tag_count            0
has_description      0
dtype: int64

In [75]:
df = df.dropna()

In [76]:

# Rename for consistency
df.rename(columns={'view_count': 'views'}, inplace=True)

# Create engagement rate
df['engagement_rate'] = (df['likes'] + df['comment_count']) / df['views']

# Monetization proxy (very important)
df['monetization_score'] = df['views'] * df['engagement_rate']

### Category Mapping

In [77]:
category_map={1:"Autos & Vehicles",2:"Music",10:"Comedy",15:"Science & Technology",17:"Anime/Animation",19:"Classics",20:"Comedy",22:"Drama"
,23:"Family",24:"Foreign",25:"Horror",26:"Sci-Fi/Fantasy",27:"Thriller",28:"Shorts",29:"Shows"
}

In [78]:
df['category_name'] = df['categoryId'].map(category_map)

In [79]:
def time_bucket(hour):
    if 5 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"

df['time_bucket'] = df['publish_hour'].apply(time_bucket)

In [80]:
# STANDARDIZE COLUMN NAMES (SNAKE_CASE)

df.rename(columns={
    'publishedAt': 'published_at',
    'channelId': 'channel_id',
    'channelTitle': 'channel_title',
    'categoryId': 'category_id',
}, inplace=True)

In [81]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)

In [82]:
# =========================================
# FINAL COLUMN ORDERING (DASHBOARD READY)
# =========================================

df = df[[
    # 🔹 1. IDENTIFIERS
    'video_id',
    'title',
    'channel_id',
    'channel_title',
    'category_id',
    'category_name',

    # 🔹 2. TIME (RAW + DERIVED)
    'published_at',
    'publish_time',
    'publish_date',
    'publish_hour',
    'time_bucket',
    'trending_date',
    'trending_year',
    'trending_month',
    'trending_day',

    # 🔹 3. PERFORMANCE (RAW METRICS)
    'views',
    'likes',
    'comment_count',
    'dislikes',

    # 🔹 4. ENGAGEMENT METRICS
    'likes_ratio',
    'comments_ratio',
    'engagement_rate',

    # 🔹 5. VIRALITY & GROWTH
    'days_to_trend',
    'trend_duration',

    # 🔹 6. MONETIZATION
    'monetization_score',

    # 🔹 7. CONTENT FEATURES
    'tags',
    'tag_count',
    'has_description',

    # 🔹 8. FLAGS
    'comments_disabled',
    'ratings_disabled'
]]

In [83]:
df.isnull().sum()

video_id              0
title                 0
channel_id            0
channel_title         0
category_id           0
category_name         0
published_at          0
publish_time          0
publish_date          0
publish_hour          0
time_bucket           0
trending_date         0
trending_year         0
trending_month        0
trending_day          0
views                 0
likes                 0
comment_count         0
dislikes              0
likes_ratio           0
comments_ratio        0
engagement_rate       0
days_to_trend         0
trend_duration        0
monetization_score    0
tags                  0
tag_count             0
has_description       0
comments_disabled     0
ratings_disabled      0
dtype: int64

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 248094 entries, 0 to 251276
Data columns (total 30 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   video_id            248094 non-null  object
 1   title               248094 non-null  object
 2   channel_id          248094 non-null  object
 3   channel_title       248094 non-null  object
 4   category_id         248094 non-null  int64
 5   category_name       248094 non-null  object
 6   published_at        248094 non-null  datetime64[ns, UTC]
 7   publish_time        248094 non-null  datetime64[ns, UTC]
 8   publish_date        248094 non-null  object
 9   publish_hour        248094 non-null  int32
 10  time_bucket         248094 non-null  object
 11  trending_date       248094 non-null  datetime64[ns, UTC]
 12  trending_year       248094 non-null  int32
 13  trending_month      248094 non-null  int32
 14  trending_day        248094 non-null  object
 15  views               248094 non-null  int64
 16  likes               248094 non-null  int64
 17  comment_count       248094 non-null  int64
 18  dislikes            248094 non-null  int64
 19  likes_ratio         248094 non-null  float64
 20  comments_ratio      248094 non-null  float64
 21  engagement_rate     248094 non-null  float64
 22  days_to_trend       248094 non-null  int64
 23  trend_duration      248094 non-null  int64
 24  monetization_score  248094 non-null  float64
 25  tags                248094 non-null  object
 26  tag_count           248094 non-null  int64
 27  has_description     248094 non-null  bool
 28  comments_disabled   248094 non-null  bool
 29  ratings_disabled    248094 non-null  bool
dtypes: bool(3), datetime64[ns, UTC](3), float64(4), int32(3), int64(8), object(9)
memory usage: 50.9+ MB

In [85]:
df.sample(5)

,video_id,title,channel_id,channel_title,category_id,category_name,published_at,publish_time,publish_date,publish_hour,...,comments_ratio,engagement_rate,days_to_trend,trend_duration,monetization_score,tags,tag_count,has_description,comments_disabled,ratings_disabled
187097,IWm_uSVBvbA,Lagna Jamva Jamvi | Vinayak Mali Comedy,UCSB-L3HN2tJoizsxR45vUFQ,Vinayak Mali,22,Drama,2023-04-16 05:35:50+00:00,2023-04-16 05:35:50+00:00,2023-04-16,5,...,0.001745,0.068990,0,6,42257.0,none,1,True,False,False
232345,zzKV_T9ybe8,지민 (Jimin) 'Closer Than This' Official MV,UC3IZKseVpdzPSBaWxBxundA,HYBE LABELS,10,Comedy,2023-12-22 05:00:02+00:00,2023-12-22 05:00:02+00:00,2023-12-22,5,...,0.014435,0.200061,4,5,1585668.0,labels hybe,1,True,False,False
148929,OguRgvA-vs0,Tom&Jerry 🥰sayoo&anvi |sangeethkumar#shorts,UCdce_0JccaDtpuv5x9Gjdyw,Sangeeth Kumar,22,Drama,2022-09-20 04:30:04+00:00,2022-09-20 04:30:04+00:00,2022-09-20,4,...,0.000143,0.063070,1,3,450308.0,none,1,True,False,False
143320,VlXa5l0RUHc,13ആം വയസ്സിൽ കുടുംബം പുലർത്താൻ രാപ്പകൽ കഷ്ടപ്പ...,UCL-UMk0yBAIxKYcyNC5iHNw,Harish Thali,24,Foreign,2022-08-22 03:24:36+00:00,2022-08-22 03:24:36+00:00,2022-08-22,3,...,0.002755,0.049435,2,5,34045.0,aju harish life news hangout live malayalam ma...,1,True,False,False
50539,f6U_W44Do4A,Fridge Tour In Tamil | Fridge Organization Tip...,UCHGktfcQq2BY_8tGPHwvm7g,Madras Samayal,26,Sci-Fi/Fantasy,2021-05-14 05:30:03+00:00,2021-05-14 05:30:03+00:00,2021-05-14,5,...,0.003632,0.039257,1,6,37637.0,tips organization fridge ideas tamil kitchen s...,1,True,False,False

In [86]:
df.to_csv('/content/drive/MyDrive/gen ai capstone/cleaned_india_youtube_data.csv', index=False)